from App.Db.Models.UploadedFiles import UploadedFile
from App.Db.Models.AdmissionForms import AdmissionForm
from App.Db.Models.AadhaarDocuments import AadhaarDocument
from App.Db.Models.TransferCertificates import TransferCertificate
from App.Db.Models.BirthCertificates import BirthCertificate
from App.Db.Models.Marksheets import Marksheet
from App.Db.Models.SrRegistry import SRRegistry
from App.Db.Models.AadhaarLookupCandidates import AadhaarLookupCandidate
from App.Db.Models.TransferCertificateCandidates import TransferCertificateCandidate
from App.Db.Models.MarksheetCandidates import MarksheetCandidate
from App.Db.Models.BirthCertificateCandidates import BirthCertificateCandidate
from App.Db.Models.AadhaarMatches import AadhaarMatch
from App.Db.Models.TcMatches import TCMatch
from App.Db.Models.MarksheetMatches import MarksheetMatch
from App.Db.Models.BirthCertificateMatches import BirthCertificateMatch
