from backend.app.db.models.uploaded_files import UploadedFile
from backend.app.db.models.admission_forms import AdmissionForm
from backend.app.db.models.aadhaar_documents import AadhaarDocument
from backend.app.db.models.transfer_certificates import TransferCertificate
from backend.app.db.models.birth_certificates import BirthCertificate
from backend.app.db.models.marksheets import Marksheet
from backend.app.db.models.sr_registry import SRRegistry
from backend.app.db.models.aadhaar_lookup_candidates import AadhaarLookupCandidate
from backend.app.db.models.transfer_certificate_candidates import TransferCertificateCandidate
from backend.app.db.models.marksheet_candidates import MarksheetCandidate
from backend.app.db.models.birth_certificate_candidates import BirthCertificateCandidate
from backend.app.db.models.aadhaar_matches import AadhaarMatch
from backend.app.db.models.tc_matches import TCMatch
from backend.app.db.models.marksheet_matches import MarksheetMatch
from backend.app.db.models.birth_certificate_matches import BirthCertificateMatch
